const ImageItems = [
  { filename: '12th F1tenth Competition - 3rd Place.jpg', title: '12th F1tenth Competition - 3rd Place.jpg', value: 45 },
  { filename: 'DeepLearning.AI TensorFlow Developer.jpg', title: 'TensorFlow Developer Certification', value: 40 },
  { filename: 'Letter Of Appreciation(2019).jpg', title: 'Letter Of Appreciation (2019)', value: 40 },
  { filename: 'Letter Of Appreciation(2020).jpg', title: 'Letter Of Appreciation (2020)', value: 40 },
  { filename: 'Google Data Analytics.jpg', title: 'Google Data Analytics', value: 40 },
  { filename: 'Code Jam 2020.jpg', title: 'Code Jam 2020', value: 35 },
  { filename: 'Code Jam 2021.jpg', title: 'Code Jam 2021', value: 35 },
  { filename: 'Kick Start 2019.jpg', title: 'Kick Start 2019', value: 35 },
  { filename: 'Kick Start 2020.jpg', title: 'Kick Start 2020', value: 35 },
  { filename: 'Hour Of Code.jpg', title: 'Hour Of Code', value: 35 },
  { filename: 'Innovatia Panoply.jpg', title: 'Innovatia Panoply', value: 30 },
  { filename: 'Hack Revolution 2019.jpg', title: 'Hack Revolution 2019', value: 30 },
  { filename: 'Hack Revolution 2020.jpg', title: 'Hack Revolution 2020', value: 30 },
  { filename: 'Imagine Hack 2020.jpg', title: 'Imagine Hack 2020', value: 30 },
  { filename: 'JPMC Virtual Internship.jpg', title: 'JPMC Virtual Internship', value: 15 },
  { filename: 'Mobile Application Development.jpg', title: 'Mobile Application Development', value: 15 },
  { filename: 'Pantechelearning AI Internship certificate.jpg', title: 'Pantechelearning AI Internship Certificate', value: 15 },
  { filename: 'Pantechelearning Data Science Internship.jpg', title: 'Pantechelearning Data Science Internship', value: 15 },
  { filename: 'Microsoft Build 2020.jpg', title: 'Microsoft Build 2020', value: 20 },
  { filename: 'Azure Cloud Services.jpg', title: 'Azure Cloud Services', value: 20 },
  { filename: 'Mohammed Misbah Zarrar GCCDIndia.jpg', title: 'Mohammed Misbah Zarrar GCCDIndia', value: 20 },
  { filename: 'Machine Learning Model Deployment using Flask.jpg', title: 'Machine Learning Model Deployment using Flask', value: 25 },
  { filename: 'Microsoft AI Classroom Series Certificate 2021.jpg', title: 'Microsoft AI Classroom Series Certificate 2021', value: 25 },
  { filename: 'Mohammed_Sep_2020_internship_4820.jpg', title: 'Mohammed Sep 2020 Internship', value: 25 },
  { filename: 'Machine Learning.jpg', title: 'Machine Learning', value: 25 },
  { filename: 'AWSOME Day Cofenerence 2022.jpg', title: 'AWSOME Day Conference 2022', value: 20 },
  { filename: 'Matlab Certificate.jpg', title: 'Matlab Certificate', value: 10 },
  { filename: 'Swift Study 2.jpg', title: 'Swift Study 2', value: 10 },
  { filename: 'Go Study 1.jpg', title: 'Go Study 1', value: 10 },
  { filename: 'JavaScript Study 5.jpg', title: 'JavaScript Study 5', value: 10 },
  { filename: 'Adobe Photoshop CS6.jpg', title: 'Adobe Photoshop CS6', value: 35 },
];
// Sort the array based on the 'value' property in descending order
ImageItems.sort((a, b) => b.value - a.value);
export default ImageItems;
