const SkillWords = [
  { text: 'C/C++', value: 40 },
  { text: 'JAVA', value: 40 },
  { text: 'Python', value: 40 },
  { text: 'MySQL', value: 40 },
  { text: 'TensorFlow', value: 40 },
  { text: 'Data Structure', value: 40 },
  
  { text: 'Machine Learning', value: 35 },
  { text: 'Computer Vision', value: 35 },
  { text: 'Embedded C', value: 35 },
  { text: 'React', value: 35 },
  
  { text: 'C#', value: 30 },
  { text: 'Git', value: 30 },
  { text: 'SDLCs', value: 30 },

  { text: 'UI/UX', value: 25 },
  { text: 'Adobe Xd', value: 25 },
  { text: 'Figma', value: 25 },
  { text: 'Flask', value: 25 },
  { text: 'HTML5', value: 25 },
  { text: 'CSS3', value: 25 },
  { text: 'JavaScript', value: 25 },

  { text: 'Android Studio', value: 20 },
  { text: 'Azure', value: 20 },
  { text: 'GCP', value: 20 },
  { text: 'AWS', value: 20 },
  { text: 'Adobe Photoshop CS6', value: 20 },

  { text: '.NET', value: 15 },
  { text: 'R', value: 15 },

  { text: 'PostgreSQL', value: 25 },
  { text: 'MongoDB', value: 25 },
  { text: 'Advance Data Structures', value: 35 },
  { text: 'Probability & Statistics', value: 25 },
  { text: 'Tableau', value: 20 },
  { text: 'ROS', value: 30 },
  { text: 'TinyML', value: 25 },
  { text: 'CUDA', value: 20 },
  { text: 'JIRA', value: 25 },
  { text: 'Docker', value: 25 },
  { text: 'QT C++', value: 25 },
  { text: 'Linux', value: 25 },
  { text: 'Node.js', value: 25 },
  { text: 'REST API', value: 25 },
  { text: 'GraghQL', value: 20 },
  { text: 'MLOps', value: 20 },
  { text: 'MatLab', value: 20 },
  { text: 'Dialogflow', value: 20 },
];
  // { text: 'Problem-solving Ability', value: 28 },
  // { text: 'Analytical Thinker', value: 30 },
  // { text: 'Quick Learner', value: 25 },
  // { text: 'Collaborative Leader', value: 22 },
  // { text: 'Self-Aware', value: 20 },
  // { text: 'Cooperative', value: 18 },
export default SkillWords